apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-api-secret
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
type: Opaque
data:
  # Application secrets
  secret-key: {{ .Values.api.env.secretKey | b64enc | quote }}
  database-url: {{ .Values.api.env.databaseUrl | b64enc | quote }}
  
  # Superuser credentials
  super-user-password: {{ .Values.api.env.superUserPassword | b64enc | quote }}